CREATE TABLE ITEM_CATEGORY(
ID VARCHAR(36) PRIMARY KEY NOT NULL,
CATEGORY_NAME VARCHAR(64),
CATEGORY_INDEX INT,
ABOVE_CATEGORY_ID VARCHAR(36),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE ITEM_ATTRIBUTE(
ID VARCHAR(36) PRIMARY KEY NOT NULL,
ATTR_NAME VARCHAR(64),
ATTR_COLUMN VARCHAR(64),
ATTR_TYPE VARCHAR(64),
IS_REQUIRED VARCHAR(4),
IS_SELECTED VARCHAR(4),
VATTR_ID VARCHAR(36),

ITEM_CATEGORY_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE ITEM_SUBSTANCE(
ID VARCHAR(36) PRIMARY KEY NOT NULL,
ITEM_NUMBER VARCHAR(64),
ITEM_MODEL VARCHAR(64),
ITEM_NAME VARCHAR(64),

ITEM_CATEGORY_ID VARCHAR(36),
ITEM_SUPPLIER_ID VARCHAR(36),
ITEM_MFRS_ID VARCHAR(36),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);


CREATE TABLE ITEM_IMAGE(
ID VARCHAR(36) PRIMARY KEY NOT NULL,
IMAGE_NAME VARCHAR(64),
IMAGE_URL VARCHAR(64),
IMAGE_REF VARCHAR(64),
IMAGE_FORMAT VARCHAR(64),
IMAGE_SIZE INT,
ITEM_SUBSTANCE_ID VARCHAR(36),
CREATOR_ID VARCHAR(36),
MODIFIER_ID VARCHAR(36),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

