CREATE TABLE ITEM_SUBSTANCE(
ID VARCHAR(36) PRIMARY KEY NOT NULL,
ITEM_NAME VARCHAR(64),
MODEL_NO VARCHAR(64),
ITEM_CATEGORY_ID VARCHAR(36),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE ITEM_ATTRIBUTE(
ID VARCHAR(36) PRIMARY KEY NOT NULL,
ATTR_NAME VARCHAR(64),
ATTR_COLUMN VARCHAR(64),
ATTR_TYPE VARCHAR(64),
IS_REQUIRED VARCHAR(4),
IS_SELECT VARCHAR(4),
VATTR_ID VARCHAR(36),

ITEM_CATEGORY_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE ITEM_SUBSTANCE(
ID VARCHAR(36) PRIMARY KEY NOT NULL,
ITEM_NAME VARCHAR(64),
MODEL_NO VARCHAR(64),
ITEM_CATEGORY_ID VARCHAR(36),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);
