CREATE TABLE REP_CATEGORY(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
CATEGORY_NAME VARCHAR(64),
PRIORITY INT,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE FRE_DEDUCT(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FRE_ORDER_ID VARCHAR(64),
ORG_ENTITY_ID VARCHAR(64),
BALANCE DOUBLE(12,4),

DEDUCT_COUNT_SALESMAN DOUBLE(12,4),
SETTLE_DONE_SALESMAN VARCHAR(64),
SETTLE_TIME_SALESMAN TIMESTAMP NULL,

DEDUCT_COUNT_SERVISE DOUBLE(12,4),
SETTLE_DONE_SERVISE VARCHAR(64),
SETTLE_TIME_SERVISE TIMESTAMP NULL,

DEDUCT_COUNT_MANIPULATOR DOUBLE(12,4),
SETTLE_DONE_MANIPULATOR VARCHAR(64),
SETTLE_TIME_MANIPULATOR TIMESTAMP NULL,

RECONCILE_TIME TIMESTAMP NULL,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);