CREATE TABLE OUT_MSG_INFO(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
MSG_TYPE VARCHAR(256),
TITILE VARCHAR(64),
CONTENT VARCHAR(256),
SEND_USER_ID VARCHAR(64),
RECEIVE_USER_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);