UPDATE MOTOR_INSURANCE SET CURRENCY='人民币', EXCHANGE_RATE=1;
UPDATE MOTOR_PETROL SET CURRENCY='人民币', EXCHANGE_RATE=1;
UPDATE MOTOR_TOLL SET CURRENCY='人民币', EXCHANGE_RATE=1;
UPDATE MOTOR_WEAL SET CURRENCY='人民币', EXCHANGE_RATE=1;