CREATE TABLE SYS_AUTH_ROLE_REP(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ROLE_ID VARCHAR(64),
REP_TEMPLATE_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);