ALTER TABLE fas_account CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fas_account CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fas_due CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fas_due CHANGE DUE_TIME DUE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fas_exchange_rate CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fas_exchange_rate CHANGE START_TIME START_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fas_invoice CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fas_invoice CHANGE RELEASE_TIME RELEASE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fas_invoice_type CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fas_invoice_type CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fas_pay CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fas_pay CHANGE APPLY_TIME APPLY_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fas_reconcile CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fas_reconcile CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_action CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_action_box CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_action_field CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_action_type CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fre_action_type CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_action_type_identity CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_audit_record CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_box CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_box_require CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_data_template CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_data_template_action_value CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_delegate CHANGE PLACE_TIME PLACE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_delegate_template CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fre_delegate_template CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_expense CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_expense_box CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_expense_type CHANGE DESCN DESCN VARCHAR(256);
ALTER TABLE fre_expense_type CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_invoice_offset CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_maintain CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_maintain_action CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_maintain_type CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_net_day CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_order_box CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_pact CHANGE SIGN_DATE SIGN_DATE TIMESTAMP DEFAULT 0;

ALTER TABLE fre_part CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_price CHANGE EFFECT_TIME EFFECT_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_seal CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;

ALTER TABLE fre_statement CHANGE CREATE_TIME CREATE_TIME TIMESTAMP DEFAULT 0;