ALTER TABLE FRE_DEDUCT ADD DEDUCT_TIME TIMESTAMP DEFAULT 0;

UPDATE FRE_DEDUCT SET STATUS='DEDUCT_PREPARED' WHERE STATUS='DEDUCTE_PREPARED'

UPDATE FRE_DEDUCT SET STATUS='DEDUCT_HAVE' WHERE STATUS='DEDUCTE_HAVE'

UPDATE FRE_DEDUCT SET STATUS='DEDUCT_REVISED' WHERE STATUS='DEDUCTE_REVISED'

UPDATE FRE_DEDUCT SET STATUS='DEDUCT_NONE' WHERE STATUS='DEDUCTE_NONE'

UPDATE FRE_DEDUCT SET STATUS='DEDUCT_SATE' WHERE STATUS='DEDUCTE_SATE'