CREATE INDEX INDEX_BV_BA ON BASIS_VALUE (BASIS_ATTR_ID);
CREATE INDEX INDEX_BV_BS ON BASIS_VALUE (BASIS_SUBSTANCE_ID);
CREATE INDEX INDEX_BV_BA_BS ON BASIS_VALUE (BASIS_ATTR_ID, BASIS_SUBSTANCE_ID);

CREATE INDEX INDEX_FAV_FF ON FRE_ACTION_VALUE (FRE_FIELD_ID);
CREATE INDEX INDEX_FAV_FA ON FRE_ACTION_VALUE (FRE_ACTION_ID);
CREATE INDEX INDEX_FAV_FF_FA ON FRE_ACTION_VALUE (FRE_FIELD_ID, FRE_ACTION_ID);