CREATE TABLE SYS_AUTH_ROLE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ROLE_NAME VARCHAR(64),
ROLE_KEY VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_AUTH_USER_ROLE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
USER_ID VARCHAR(64),
ROLE_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_AUTH_POSITION_ROLE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
POSITION_ID VARCHAR(64),
ROLE_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_AUTH_ROLE_RESOURCE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ROLE_ID VARCHAR(64),
RESOURCE_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_AUTH_RESOURCE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
RESOURCE_NAME VARCHAR(64),
RESOURCE_KEY VARCHAR(64),
RESOURCE_URL VARCHAR(64),
RESOURCE_TYPE VARCHAR(64),
ICON VARCHAR(64),
ENABLE VARCHAR(64),
PARENT_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE SYS_AUTH_CONSTANT(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
AUTH_TYPE VARCHAR(64),
CONSTANT_NAME VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_AUTH_ROLE_REP(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ROLE_ID VARCHAR(64),
REP_TEMPLATE_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);