CREATE TABLE AUTH_SYS_PRIVILEGE_MASTER(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
PRIVILEGE_TYPE VARCHAR(64),
PRIVILEGE_MASTER_ID VARCHAR(64),
PRIVILEGE_MASTER_VALUE VARCHAR(64),
PRIVILEGE_ACCESS_ID VARCHAR(64),
PRIVILEGE_ACCESS_VALUE VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);