CREATE TABLE BASIS_SUBSTANCE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
BASIS_SUBSTANCE_TYPE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_SUBSTANCE_TYPE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TYPE_NAME VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_ATTR(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ATTR_NAME VARCHAR(64),
ATTR_COLUMN VARCHAR(64),
ATTR_TYPE VARCHAR(64),
REQUIRED VARCHAR(64),
CAN_SELECT VARCHAR(64),
VATTR_ID VARCHAR(64),
VCLS_ID VARCHAR(64),
VCOLUMN VARCHAR(64),
VFILTER_ID VARCHAR(64),

BASIS_SUBSTANCE_TYPE_ID VARCHAR(64),
DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_VALUE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
STRING_VALUE VARCHAR(64),
TEXT_VALUE TEXT,
DOUBLE_VALUE DOUBLE(12,4),
INT_VALUE INT,
DATE_VALUE TIMESTAMP,

BASIS_ATTR_ID VARCHAR(64),
BASIS_SUBSTANCE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_STATUS(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
STATUS_TEXT VARCHAR(64),
BASIS_SUBSTANCE_TYPE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_APPLICATION(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
APPLICATION_NAME VARCHAR(64),
READONLY VARCHAR(64),
FILTER_TEXT VARCHAR(64),
BASIS_SCHEMA_ID VARCHAR(64),
BASIS_SUBSTANCE_TYPE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_SCHEMA(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
SCHEMA_NAME VARCHAR(64),
BASIS_SUBSTANCE_TYPE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_STATUS_ATTR(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
BASIS_STATUS_ID VARCHAR(64),
BASIS_ATTR_ID VARCHAR(64),
READONLY VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BASIS_MENU(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
MENU_NAME VARCHAR(64),
MENU_KEY VARCHAR(64),
BASIS_SUBSTANCE_TYPE_ID VARCHAR(64),
BASIS_APPLICATION_ID VARCHAR(64),
ENABLE VARCHAR(64),
PARENT_ID VARCHAR(64),
CONF_PRIME_URL VARCHAR(64),
CONF_MANAGE_URL VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);