CREATE TABLE BPM_MAIL_TEMPLATE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TEMPLATE_NAME VARCHAR(64),
SUBJECT VARCHAR(64),
CONTENT VARCHAR(128),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BPM_CONF_CATEGORY(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
CATEGORY_NAME VARCHAR(64),
PRIORITY INT,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BPM_CONF_BASIS(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
BPM_KEY VARCHAR(64),
BASIS_SUBSTANCE_TYPE_ID VARCHAR(64),
BASIS_APPLICATION_ID VARCHAR(64),
BPM_CONF_CATEGORY_ID VARCHAR(64),
CONF_PRIME_URL VARCHAR(64),
CONF_MANAGE_URL VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE BPM_CONF_NODE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
PD_ID VARCHAR(64),
PD_KEY VARCHAR(64),
PD_NAME VARCHAR(64),
TD_KEY VARCHAR(64),
TD_NAME VARCHAR(64),
TD_ASSIGNEE_ID VARCHAR(64),
TD_CANDIDATE_GROUP_ID VARCHAR(64),
TD_LISTNERS VARCHAR(64),
DUE_DATE VARCHAR(64),
SOURCE_STATUS VARCHAR(64),
TARGET_STATUS VARCHAR(64),
ON_CREATE VARCHAR(64),
ON_COMPLETE VARCHAR(64),
BASIS_STATUS_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE BPM_CONF_AUTH(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
AUTH_TYPE VARCHAR(64),
BPM_NODE_ID VARCHAR(64),
AUTH_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE BPM_CONF_DELEGATE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
DELEGATE_TYPE VARCHAR(64),
BPM_CONF_BASIS_ID VARCHAR(64),
TASK_ASSIGNEE_ID VARCHAR(64),
TASK_AGENT_ID VARCHAR(64),
START_TIME TIMESTAMP NULL,
END_TIME TIMESTAMP NULL,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);