CREATE TABLE SYS_BUSI_SCHEMA(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
SCHEMA_NAME VARCHAR(64),
BUSI_CLS_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);
