CREATE TABLE CAR_DRIVER(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
DRIVER_TYPE VARCHAR(64),
DISPLAY_NAME VARCHAR(64),
GENDER VARCHAR(64),
TELEPHONE VARCHAR(64),
ADRESS VARCHAR(64),

DRIVING_NUMBER VARCHAR(64),
QUASI_TYPE VARCHAR(64),
CERTIFICATION VARCHAR(64),
REG_TIME TIMESTAMP DEFAULT 0,
VALID_TIME TIMESTAMP DEFAULT 0,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE CAR_TRUCK(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TRUCK_CATEGORY VARCHAR(64),
TRUCK_TYPE VARCHAR(64),
HEADSTOCK_NUMBER VARCHAR(64),
TRAILER_NUMBER VARCHAR(64),

HEADSTOCK_FUND DOUBLE(12,4),
TRAILER_FUND DOUBLE(12,4),

HEADSTOCK_DEPRECIATION DOUBLE(12,4),
TRAILER_DEPRECIATION DOUBLE(12,4),

MANUFACTURER VARCHAR(64),
PURCHASE_TIME TIMESTAMP DEFAULT 0,
ANNUAL_TIME TIMESTAMP DEFAULT 0,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE CAR_JOURNEY(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
JOURNEY_NUMBER VARCHAR(64),
JOURNEY_TYPE VARCHAR(64),
JOURNEY_ITEM VARCHAR(64),
JOURNEY_TIME TIMESTAMP DEFAULT 0,
DESTINATION VARCHAR(64),

OUT_KEY VARCHAR(64),
OUT_PARK VARCHAR(64),
OUT_TIME TIMESTAMP DEFAULT 0,
OUT_KILOMETER_COUNT INT,
RETURN_KEY VARCHAR(64),
RETURN_PARK VARCHAR(64),
RETURN_TIME TIMESTAMP DEFAULT 0,
RETURN_KILOMETER_COUNT INT,

CAR_DRIVER_ID VARCHAR(64),
CAR_TRUCK_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE CAR_PETROL(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
LUBRICATE_CAPACITY DOUBLE(12,4),
LUBRICATE_TIME TIMESTAMP DEFAULT 0,
CURRENCY VARCHAR(64),
EXCHANGE_RATE DOUBLE(12,4),
MONEY_COUNT DOUBLE(12,4),
FAS_INVOICE_TYPE_ID VARCHAR(64),

KILOMITER_COUNT DOUBLE(12,4),
FUEL_CONSUMPTION_LAST DOUBLE(12,4),
FUEL_CONSUMPTION_MONTH DOUBLE(12,4),

CAR_TRUCK_ID VARCHAR(64),
CAR_DRIVER_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);