CREATE TABLE CORE_WHITE_LIST(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
WHITE_SCOPE VARCHAR(64),
WHITE_ADDRESS VARCHAR(64),
START_TIME TIMESTAMP NULL,
END_TIME TIMESTAMP NULL,
USER_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);