--电子词典
CREATE TABLE SYS_DIC_VALUE_CLASS(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
CLS_NAME VARCHAR(64),
TABLE_NAME VARCHAR(64),
DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_DIC_VALUE_ATTR(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ATTR_NAME VARCHAR(64),
COLUMN_NAME VARCHAR(64),
VCLS_ID VARCHAR(64),
DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_DIC_VALUE_DICTIONARY(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
VALUE_CONTENT VARCHAR(64),
VATTR_ID VARCHAR(64),
DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SYS_DIC_VALUE_FILTER(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FILTER_TEXT VARCHAR(256),
VCLS_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);