CREATE TABLE OUT_DISK_INFO(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FILE_NAME VARCHAR(64),
FILE_SUFFIX VARCHAR(64),
FILE_REF VARCHAR(64),
FILE_VERSION VARCHAR(64),
FILE_DIR VARCHAR(64),
FILE_SIZE BIGINT,

CREATOR_ID VARCHAR(64),
MODIFIER_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE OUT_DISK_SHARE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
SHARE_TYPE VARCHAR(64),
SHARE_TIME TIMESTAMP DEFAULT 0,
EXPIRE_TIME TIMESTAMP DEFAULT 0,
COUNT_VIEW INT,
COUNT_SAVE INT,
COUNT_DOWNLOAD INT,

OUT_DISK_INFO_ID VARCHAR(64),
SHARER_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE OUT_DISK_ACL(
ID VARCHAR(64) PRIMARY KEY NOT NULL,

OUT_DISK_SHARE_ID VARCHAR(64),
ACCESSARY_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);