CREATE TABLE FRE_EXPENSE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
EXPENSE_NUMBER VARCHAR(64),
INCOME_OR_EXPENSE VARCHAR(64),
PRICE VARCHAR(64),
ACTUAL VARCHAR(64),

FAS_INVOICE_TYPE_ID VARCHAR(64),
FRE_EXPENSE_TYPE_ID VARCHAR(64),
FRE_PART_ID_A VARCHAR(64),
FRE_PART_ID_B VARCHAR(64),
FRE_ORDER_ID VARCHAR(64),
FRE_PRICE_ID VARCHAR(64),
FRE_ACTION_ID VARCHAR(64),
FRE_BOX_REQUIRE_ID VARCHAR(64),
FRE_STATEMENT_ID VARCHAR(64),

COUNT_UNIT VARCHAR(64),
CURRENCY VARCHAR(64),
EXCHANGE_RATE VARCHAR(64),
PREDICT_COUNT DOUBLE(12,4),
ACTUAL_COUNT DOUBLE(12,4),

USER_ID VARCHAR(64),
ORG_ENTITY_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_EXPENSE_TYPE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TYPE_NAME VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_STATEMENT(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
STATEMENT_NUMBER VARCHAR(64),
INCOME_OR_EXPENSE VARCHAR(64),
FAS_INVOICE_TYPE_ID VARCHAR(64),
FRE_PART_ID_A VARCHAR(64),
FRE_PART_ID_B VARCHAR(64),

CURRENCY_RMB VARCHAR(64),
EXCHANGE_RATE_RMB DOUBLE(12,4),
MONEY_COUNT_RMB DOUBLE(12,4),
ELIMINATE_COUNT_RMB DOUBLE(12,4),
REMAIN_COUNT_RMB DOUBLE(12,4),

CURRENCY_DOLLAR VARCHAR(64),
EXCHANGE_RATE_DOLLAR DOUBLE(12,4),
MONEY_COUNT_DOLLAR DOUBLE(12,4),
ELIMINATE_COUNT_DOLLAR DOUBLE(12,4),
REMAIN_COUNT_DOLLAR DOUBLE(12,4),

USER_ID VARCHAR(64),
ORG_ENTITY_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_INVOICE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
INCOME_OR_EXPENSE VARCHAR(64),
CURRENCY VARCHAR(64),
EXCHANGE_RATE DOUBLE(12,4),
MONEY_COUNT DOUBLE(12,4),
ELIMINATE_COUNT DOUBLE(12,4),
REMAIN_COUNT DOUBLE(12,4),

RELEASE_TIME TIMESTAMP,
CLAIM_TIME TIMESTAMP,
ELIMINATE_TIME TIMESTAMP,
EFFECT_TIME TIMESTAMP,
period INT,

FRE_PART_ID VARCHAR(64),
FRE_STATEMENT_ID VARCHAR(64),
FAS_INVOICE_ID VARCHAR(64),
FAS_INVOICE_TYPE_ID VARCHAR(64),
USER_ID VARCHAR(64),
ORG_ENTITY_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_PRICE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
INCOME_OR_EXPENSE VARCHAR(64),
ACTUAL VARCHAR(64),
REGULAR VARCHAR(64),
MONEY_COUNT DOUBLE(12,4),
ACTUAL_COUNT DOUBLE(12,4),
PERIOD INT,
COUNT_UNIT VARCHAR(64),
CURRENCY VARCHAR(64),
EXCHANGE_RATE VARCHAR(64),
METER_TYPE VARCHAR(64),
EFFECT_TIME TIMESTAMP,

FAS_INVOICE_TYPE_ID VARCHAR(64),
FRE_PART_ID VARCHAR(64),
FRE_PACT_ID VARCHAR(64),
FRE_EXPENSE_TYPE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);