CREATE TABLE FRE_DELEGATE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
DELEGATE_NUMBER VARCHAR(64),
EXECUTE_STATUS VARCHAR(64),
LOCK_STATUS VARCHAR(64),
PLACE_TIME TIMESTAMP,
DELEGATE_FILE VARCHAR(64),
FRE_ACTION_ID VARCHAR(64),
FRE_PART_ID VARCHAR(64),
ORG_ENTITY_ID VARCHAR(64),
USER_ID VARCHAR(64),
DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE FRE_DELEGATE_TEMPLATE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TEMPLATE_NAME VARCHAR(64),
TEMPLATE_FILE VARCHAR(64),
REGION_PARAM VARCHAR(256),
DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_SEAL(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
SEAL_NUMBER VARCHAR(64),
SEAL_TYPE VARCHAR(64),
SEAL_BELONG VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_PART(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
PART_NAME VARCHAR(64),
PART_TYPE VARCHAR(64),
INTERNAL VARCHAR(64),
PART_ADDRESS VARCHAR(128),
PART_CHARGER VARCHAR(64),
PART_CONTACT VARCHAR(64),
PART_REG_ADDRESS VARCHAR(128),
PART_EXP_ADDRESS VARCHAR(128),
PART_FAX VARCHAR(64),
PART_MAIL VARCHAR(64),
ENGAGE_SCOPE VARCHAR(64),

SALE_MAN VARCHAR(64),
DELEGATE_STATUS VARCHAR(64),
PUBLIC_STATUS VARCHAR(64),

BANK_NAME_RMB VARCHAR(64),
BANK_ACCOUNT_RMB VARCHAR(64),
BANK_NAME_DOLLAR VARCHAR(64),
BANK_ACCOUNT_DOLLAR VARCHAR(64),

ORG_ENTITY_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);