CREATE TABLE FRE_DATA_TEMPLATE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TEMPLATE_NAME VARCHAR(64),
FRE_ACTION_ID VARCHAR(64),
USER_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_DATA_TEMPLATE_ACTION_VALUE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FRE_DATA_TEMPLATE_ID VARCHAR(64),
FRE_ACTION_VALUE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE FRE_ACTION_TYPE_IDENTITY(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FRE_ACTION_TYPE_ID VARCHAR(64),
ASSIGNEE_USER_ID VARCHAR(64),
CANDIDATE_GROUP_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_STATEMENT_OFFSET(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
OFFSET_TYPE VARCHAR(64),
FRE_STATEMENT_ID_A VARCHAR(64),
FRE_STATEMENT_ID_B VARCHAR(64),

ELIMINATE_COUNT_DOLLAR_A DOUBLE(12,4),
ELIMINATE_COUNT_DOLLAR_B DOUBLE(12,4),
ELIMINATE_COUNT_RMB_A DOUBLE(12,4),
ELIMINATE_COUNT_RMB_B DOUBLE(12,4),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_INVOICE_OFFSET(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
OFFSET_TYPE VARCHAR(64),
FRE_INVOICE_ID_A VARCHAR(64),
FRE_INVOICE_ID_B VARCHAR(64),

ELIMINATE_COUNT_DOLLAR_A DOUBLE(12,4),
ELIMINATE_COUNT_DOLLAR_B DOUBLE(12,4),
ELIMINATE_COUNT_RMB_A DOUBLE(12,4),
ELIMINATE_COUNT_RMB_B DOUBLE(12,4),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_NET_DAY(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
REGULAR VARCHAR(64),
INCOME_OR_EXPENSE VARCHAR(64),
CURRENCY VARCHAR(64),
FRE_PART_ID VARCHAR(64),
PERIOD INT,
DELAY_MONTH INT,
REGULAR_DAY INT,

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE FRE_AUDIT_RECORD(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TARGET_ID VARCHAR(64),
SOURCE_STATUS VARCHAR(64),
TARGET_STATUS VARCHAR(64),
USER_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE FRE_EXPENSE_BOX(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FRE_EXPENSE_ID VARCHAR(64),
FRE_ORDER_BOX_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_ACTION_BOX(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FRE_ACTION_ID VARCHAR(64),
FRE_ORDER_BOX_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);
