CREATE TABLE FRE_ORDER(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ORDER_NUMBER VARCHAR(64),
SALESMAN VARCHAR(64),
MANIPULATOR VARCHAR(64),
ORDER_SCOPE VARCHAR(64),

FIRST_TYPE VARCHAR(64),
SECOND_TYPE VARCHAR(64),
THIRD_TYPE VARCHAR(64),
FOURTH_TYPE VARCHAR(64),
DELEGATE_PART VARCHAR(64),
DELEGATE_NUMBER VARCHAR(64),
DELEGATE_CONTACT VARCHAR(64),
COMMISSION VARCHAR(64),

CARGO_OWNER VARCHAR(64),
CARGO_NAME VARCHAR(64),
CARGO_AMOUNT VARCHAR(64),
CARGO_WEIGHT DOUBLE(12,4),
CARGO_CAPACITY DOUBLE(12,4),
PLACE_TIME TIMESTAMP NULL,
FINISH_TIME TIMESTAMP NULL,

HARD_COEFFICIENT VARCHAR(64),
EXPENSE_STATUS VARCHAR(64),
ORDER_STATUS VARCHAR(64),

CREATOR_USER_ID VARCHAR(64),
ORG_ENTITY_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);




CREATE TABLE FRE_BOX(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
BOX_NUMBER VARCHAR(64),
BOX_TYPE VARCHAR(64),
BOX_BELONG VARCHAR(64),
BOX_CONDITION VARCHAR(256),
EMPTY_STATUS VARCHAR(64),
INOUT_STATUS VARCHAR(64),
PUT_STATUS VARCHAR(64),
BOX_SOURCE VARCHAR(64),
EVENT_STATUS VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_MAINTAIN(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
FRE_MAINTAIN_TYPE_ID VARCHAR(64),
FRE_ORDER_ID VARCHAR(64),
PARENT_MAINTAIN_ID VARCHAR(64),
DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE FRE_MAINTAIN_TYPE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TYPE_NAME VARCHAR(64),
PRIORITY INT,
DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);



CREATE TABLE FRE_BOX_REQUIRE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
BOX_SOURCE VARCHAR(64),
BOX_TYPE VARCHAR(64),
BOX_BELONG VARCHAR(64),
BOX_CONDITION VARCHAR(256),
BOX_COUNT INT,
BEGIN_STATION VARCHAR(64),
ARRIVE_STATION VARCHAR(64),
FRE_ORDER_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE FRE_ORDER_BOX(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
WEIGHT DOUBLE(12,4),
CAPACITY DOUBLE(12,4),
FRE_BOX_ID VARCHAR(64),
FRE_SEAL_ID VARCHAR(64),
FRE_BOX_REQUIRE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);