
CREATE TABLE FRE_PACT(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
PACT_NUMBER VARCHAR(64),
PACT_TITLE VARCHAR(64),
PACT_TYPE VARCHAR(64),
INCOME_OR_EXPENSES VARCHAR(64),
PART_A VARCHAR(64),
PART_B VARCHAR(64),
PART_C VARCHAR(64),
SIGN_DATE TIMESTAMP,
EFFECT_DATE TIMESTAMP,
CUT_OFF_DATE TIMESTAMP,
PAY_TYPE VARCHAR(64),
DEFAULT_RATE VARCHAR(64),
DEFAULT_SETTLE_DAYS INT,
CURRENCY VARCHAR(64),
MONEY_COUNT DOUBLE,
PACT_CONTENT VARCHAR(512),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);