CREATE TABLE QUARTZ_CRON(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
CRON_NAME VARCHAR(64),
CRON_EXPRESSION VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE QUARTZ_GROUP(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
GROUP_NAME VARCHAR(64),
GROUP_KEY VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE QUARTZ_TASK(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
TASK_NAME VARCHAR(64),
TASK_KEY VARCHAR(64),
SPRING_ID VARCHAR(64),
BEAN_CLASS VARCHAR(64),
METHOD_NAME VARCHAR(64),

QUARTZ_GROUP_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);


CREATE TABLE QUARTZ_JOB(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
JOB_STATUS VARCHAR(64),
CONCURRENT VARCHAR(64),
START_TIME TIMESTAMP NULL,
END_TIME TIMESTAMP NULL,

QUARTZ_CRON_ID VARCHAR(64),
QUARTZ_TASK_ID VARCHAR(64),

USER_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);

CREATE TABLE SYS_AUTH_ROLE_QUARTZ(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
ROLE_ID VARCHAR(64),
QUARTZ_TASK_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
)