CREATE TABLE REP_TEMPLATE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,

TEMPLATE_NAME VARCHAR(64),
TEMPLATE_TYPE VARCHAR(64),
TEMPLATE_FILE VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE REP_IS(
ID VARCHAR(64) PRIMARY KEY NOT NULL,

TEMPLATE_ID VARCHAR(64),
TEMPLATE_STREAM MEDIUMBLOB,

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE REP_DATA_SOURCE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,

DATA_SOURCE_NAME VARCHAR(64),
DATA_SOURCE_KEY VARCHAR(64),
SQL_TEXT VARCHAR(512),

REP_TEMPLATE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE REP_PARAM(
ID VARCHAR(64) PRIMARY KEY NOT NULL,

PARAM_NAME VARCHAR(64),
PARAM_COLUMN VARCHAR(64),
PARAM_TYPE VARCHAR(64),
DEAULT_VALUE VARCHAR(64),

STRING_VALUE VARCHAR(64),
INT_VALUE INT,
DOUBLE_VALUE DOUBLE(12, 4),
DATE_VALUE TIMESTAMP NULL,

REQUIRED VARCHAR(64),
CAN_SELECT VARCHAR(64),
VATTR_ID VARCHAR(64),
VCLS_ID VARCHAR(64),
VFILTER_ID VARCHAR(64),
VCOLUMN VARCHAR(64),

REP_TEMPLATE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE REP_SET(
ID VARCHAR(64) PRIMARY KEY NOT NULL,

SET_TYPE VARCHAR(64),
ENABLE VARCHAR(64),
FIRST_ROW VARCHAR(64),
LAST_ROW VARCHAR(64),
FIRST_COLUMN VARCHAR(64),
LAST_COLUMN VARCHAR(64),

REP_TEMPLATE_ID VARCHAR(64),

DESCN VARCHAR(128),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP ,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);


CREATE TABLE REP_CATEGORY(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
CATEGORY_NAME VARCHAR(64),
PRIORITY INT,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP DEFAULT 0,
MODIFY_TIME TIMESTAMP DEFAULT 0,
DISP_INX INT
);