CREATE TABLE SALARY_GRADE(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
GRADE_COUNT INT,
BASIC_SALARY DOUBLE(12,4),
POST_SALARY DOUBLE(12,4),
START_TIME TIMESTAMP NULL,
END_TIME TIMESTAMP NULL,
USER_ID VARCHAR(64),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SALARY_BASIC(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
PREDICT_SALARY DOUBLE(12,4),
PREDICT_DEBIT DOUBLE(12,4),

PREDICT_PAYMENT DOUBLE(12,4),
ACTUAL_PAYMENT DOUBLE(12,4),
SALARY_YEAR INT,
SALARY_MONTH INT,

COMPUTE_TIME TIMESTAMP NULL,
CONFIRM_TIME TIMESTAMP NULL,

SALARY_GRADE_ID VARCHAR(64),

ENDOWMENT_INDIVIDUAL DOUBLE(12,4),
ENDOWMENT_COMPANY DOUBLE(12,4),

MEDICAL_INDIVIDUAL DOUBLE(12,4),
MEDICAL_COMPANY DOUBLE(12,4),

UNEMPLOYMENT_INDIVIDUAL DOUBLE(12,4),
UNEMPLOYMENT_COMPANY DOUBLE(12,4),

INJURY_INDIVIDUAL DOUBLE(12,4),
INJURY_COMPANY DOUBLE(12,4),

MATERNITY_INDIVIDUAL DOUBLE(12,4),
MATERNITY_COMPANY DOUBLE(12,4),

HOSING_INDIVIDUAL DOUBLE(12,4),
HOSING_COMPANY DOUBLE(12,4),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);

CREATE TABLE SALARY_BONUS(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
PREDICT_SALARY DOUBLE(12,4),
PREDICT_DEBIT DOUBLE(12,4),

PREDICT_PAYMENT DOUBLE(12,4),
ACTUAL_PAYMENT DOUBLE(12,4),
SALARY_YEAR INT,
SALARY_MONTH INT,

COMPUTE_TIME TIMESTAMP NULL,
CONFIRM_TIME TIMESTAMP NULL,

SALARY_GRADE_ID VARCHAR(64),

POST_BONUS DOUBLE(12,4),
PERFORMANCE_BONUS DOUBLE(12,4),
DEDUCT_BONUS DOUBLE(12,4),
EXECUTIVE_BONUS DOUBLE(12,4),
RISK_BONUS DOUBLE(12,4),
SPECIAL_BONUS DOUBLE(12,4),

SENIORITY_SUBSIDY DOUBLE(12,4),
HOSING_SUBSIDY DOUBLE(12,4),
LUNCH_SUBSIDY DOUBLE(12,4),
OVERTIME_SUBSIDY DOUBLE(12,4),
PROTECT_SUBSIDY DOUBLE(12,4),

EXECUTIVE_DEBIT DOUBLE(12,4),
RISK_DEBIT DOUBLE(12,4),
OTHER_DEBIT DOUBLE(12,4),

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP,
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);