CREATE TABLE V_VERSION(
ID VARCHAR(64) PRIMARY KEY NOT NULL,
VERSION VARCHAR(64) UNIQUE,
IS_SUCCESS VARCHAR(64),
EXECUTE_TIME TIMESTAMP NULL,

DESCN VARCHAR(256),
STATUS VARCHAR(64),
CREATE_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
MODIFY_TIME TIMESTAMP,
DISP_INX INT
);